name: 'kolesa_dwh'
version: '1.0.0'
config-version: 2

profile: 'kolesa_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kolesa_dwh:
    gold:
      +materialized: table
      +schema: gold
    silver:
      +materialized: table
      +schema: silver

vars:
  warehouse_db: "warehouse"
  warehouse_schema: "warehouse"

