kolesa_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5435') | as_number }}"
      user: "{{ env_var('WAREHOUSE_USER', 'warehouse') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD', 'warehouse') }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'warehouse') }}"
      schema: warehouse
      threads: 4

